version: '3'

services:
  web:
    image: ghcr.io/mkaraki/mc-container-manager:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
      - /home/mc:/mc
#      - type: bind
#        source: ./config.php
#        target: /var/www/html/_config.php:ro
    ports:
      - 25500:80

  filemanager:
    image: ghcr.io/mkaraki/mc-container-manager-tinyfilemanager:master
    volumes:
      - /home/mc:/mc
    user: 0:0
    ports:
      - 25501:80
