name: Docker Image CI (filemanager)

on:
  push:
    paths:
      - Dockerfile.tinyfilemanager
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.tinyfilemanager --tag my-image-name:$(date +%s)
